-- PostgreSQL 15+ : exécuter dans une base mediflow déjà créée.
CREATE TABLE utilisateurs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    mot_de_passe_hash VARCHAR(60) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('INFIRMIER', 'GENERALISTE'))
);

-- Dans ce premier livrable, une ligne représente une arrivée d'un patient.
-- Le numéro de sécurité sociale n'est donc pas unique entre plusieurs visites.
CREATE TABLE patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    date_naissance DATE NOT NULL,
    numero_securite_sociale VARCHAR(30) NOT NULL,
    tension_arterielle VARCHAR(7) NOT NULL,
    frequence_cardiaque INTEGER NOT NULL CHECK (frequence_cardiaque BETWEEN 20 AND 250),
    temperature DOUBLE PRECISION NOT NULL CHECK (temperature BETWEEN 30 AND 45),
    frequence_respiratoire INTEGER NOT NULL CHECK (frequence_respiratoire BETWEEN 5 AND 80),
    date_arrivee TIMESTAMP NOT NULL
);
CREATE INDEX idx_patients_date_arrivee ON patients(date_arrivee);

-- Structure anticipée, écriture non implémentée dans cette version partielle.
CREATE TABLE consultations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL UNIQUE REFERENCES patients(id),
    medecin_id BIGINT NOT NULL REFERENCES utilisateurs(id),
    motif TEXT NOT NULL,
    observations TEXT NOT NULL,
    diagnostic TEXT NOT NULL,
    traitement TEXT NOT NULL,
    cout NUMERIC(10,2) NOT NULL DEFAULT 150.00 CHECK (cout = 150.00),
    statut VARCHAR(20) NOT NULL DEFAULT 'TERMINEE' CHECK (statut = 'TERMINEE'),
    date_consultation TIMESTAMP NOT NULL
);
